export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";

export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const GET_ADMIN_REQUEST = 'GET_ADMIN_REQUEST';
export const GET_ADMIN_SUCCESS = 'GET_ADMIN_SUCCESS';
export const GET_ADMIN_FAILURE = 'GET_ADMIN_FAILURE';

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const DELETE_DATASET_SUCCESS = "DELETE_DATASET_SUCCESS";
export const DELETE_GRAPH_SUCCESS = "DELETE_GRAPH_SUCCESS";

export const FETCH_DATASETS_REQUEST = "FETCH_DATASETS_REQUEST";
export const FETCH_DATASETS_SUCCESS = "FETCH_DATASETS_SUCCESS";
export const FETCH_DATASETS_FAIL = "FETCH_DATASETS_FAIL";

export const FETCH_GRAPHS_REQUEST = "FETCH_GRAPHS_REQUEST";
export const FETCH_GRAPHS_SUCCESS = "FETCH_GRAPHS_SUCCESS";
export const FETCH_GRAPHS_FAIL = "FETCH_GRAPHS_FAIL";
